stocks:
  "002436":
    name: 兴森科技
    cost: 50.015
    shares: 200
    sector: PCB  
  "002156":
    name: 通富微电
    cost: 74.041
    shares: 100
    sector: Semiconductor
  "002262":
    name: 恩华药业
    cost: 41.891
    shares: 200
    sector: Medicine
  "000901":
    name: 航天科技
    cost: 28.488
    shares: 100
    sector: Defense
  "600062":
    name: 华润双鹤
    cost: 22.543
    shares: 200
    sector: Medicine
  "600483":
    name: 福能股份
    cost: 11.759
    shares: 300
    sector: Power
  "000066":
    name: 中国长城
    cost: 19.641
    shares: 100
    sector: Semiconductor

